language: ruby
os: linux
dist: bionic
services:
  - docker
script:
  - ./build
deploy:
  provider: script
  script: docker_push
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE =~ ^(push|cron)$
