language: shell
os: linux
dist: bionic

services:
  - docker

env:
  - TAG=latest
  - TAG=rolling
  - TAG=devel

script:
  - docker build -t $DOCKER_REPO:$TAG .

deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = cron
